[pytest]

# Defining the markers for Pytest
markers =
    unit: marks tests as unit tests (fast, isolated, no external dependencies)
    integration: marks tests as integration tests (may hit DB, network, filesystem, etc.)
    slow: marks tests as slow-running

# Fail if someone uses an unregistered marker
addopts = --strict-markers -v
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*